# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEuropeanCallPrice <- function(nInt, strike, spot, vol, r, expiry, barrier, nReps = 10000L) {
    .Call(`_EuropeanUpAndOutCall_getEuropeanCallPrice`, nInt, strike, spot, vol, r, expiry, barrier, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_EuropeanUpAndOutCall_rcpp_hello_world`)
}

